from __future__ import annotations

from dataclasses import dataclass


GB = 1e9


@dataclass(frozen=True, slots=True)
class ModelSpec:
    """Static metadata sufficient for M0/M1 architecture exploration.

    Parameter counts are authoritative inputs when published by the model vendor.
    The simulator deliberately does not instantiate or download model weights.
    """

    key: str
    name: str
    total_parameters: float
    active_parameters: float
    num_layers: int
    hidden_size: int
    num_experts: int = 0
    experts_per_token: int = 0
    shared_experts: int = 0
    dense_layers: int = 0
    moe_intermediate_size: int | None = None
    context_length: int | None = None
    architecture: str = "dense"
    source: str = ""
    notes: str = ""

    @property
    def moe_layers(self) -> int:
        return max(0, self.num_layers - self.dense_layers) if self.num_experts else 0

    @property
    def shared_expert_parameters_per_moe_layer(self) -> float:
        """Explicit parameters in the always-active shared-expert MLP.

        Kimi/GLM implement shared experts as one gated MLP whose intermediate
        width is moe_intermediate_size * shared_experts. A gated MLP has gate,
        up and down matrices, hence 3 * hidden * intermediate parameters.
        """
        if not self.shared_experts or not self.moe_intermediate_size or not self.moe_layers:
            return 0.0
        return 3.0 * self.hidden_size * self.moe_intermediate_size * self.shared_experts

    @property
    def shared_expert_parameters_total(self) -> float:
        return self.shared_expert_parameters_per_moe_layer * self.moe_layers

    def storage_bytes(self, bits_per_weight: float, overhead_fraction: float = 0.0) -> float:
        _validate_bits(bits_per_weight)
        _validate_overhead(overhead_fraction)
        return self.total_parameters * bits_per_weight / 8.0 * (1.0 + overhead_fraction)

    def mixed_storage_bytes(
        self,
        bits_per_weight: float,
        overhead_fraction: float = 0.0,
        *,
        shared_expert_bits: float | None = None,
    ) -> float:
        """Weight storage with an optional precision override for shared experts."""
        base = self.storage_bytes(bits_per_weight, overhead_fraction)
        if shared_expert_bits is None or not self.shared_expert_parameters_total:
            return base
        _validate_bits(shared_expert_bits)
        scale = 1.0 + overhead_fraction
        delta_bits = shared_expert_bits - bits_per_weight
        return base + self.shared_expert_parameters_total * delta_bits / 8.0 * scale

    def active_weight_bytes(self, bits_per_weight: float, overhead_fraction: float = 0.0) -> float:
        _validate_bits(bits_per_weight)
        _validate_overhead(overhead_fraction)
        return self.active_parameters * bits_per_weight / 8.0 * (1.0 + overhead_fraction)

    def mixed_active_weight_bytes(
        self,
        bits_per_weight: float,
        overhead_fraction: float = 0.0,
        *,
        shared_expert_bits: float | None = None,
    ) -> float:
        """Active weight bytes with optional higher/lower shared-expert precision."""
        base = self.active_weight_bytes(bits_per_weight, overhead_fraction)
        if shared_expert_bits is None or not self.shared_expert_parameters_total:
            return base
        _validate_bits(shared_expert_bits)
        scale = 1.0 + overhead_fraction
        delta_bits = shared_expert_bits - bits_per_weight
        return base + self.shared_expert_parameters_total * delta_bits / 8.0 * scale

    def hidden_bytes(self, activation_bits: float = 16.0) -> float:
        _validate_bits(activation_bits)
        return self.hidden_size * activation_bits / 8.0

    def minimum_bits_for_capacity(self, capacity_bytes: float, overhead_fraction: float = 0.0) -> float:
        """Maximum average bits/weight that fit into the supplied capacity."""
        if capacity_bytes <= 0:
            raise ValueError("capacity_bytes must be positive")
        _validate_overhead(overhead_fraction)
        return capacity_bytes * 8.0 / (self.total_parameters * (1.0 + overhead_fraction))

    def approximate_moe_network_bytes(
        self,
        *,
        activation_bits: float = 16.0,
        send_and_return: bool = True,
        remote_expert_fraction: float = 1.0,
    ) -> float:
        """Approximate activation traffic generated by routed experts per token."""
        if not 0.0 <= remote_expert_fraction <= 1.0:
            raise ValueError("remote_expert_fraction must be in [0, 1]")
        if not self.num_experts or not self.experts_per_token:
            return 0.0
        multiplier = 2.0 if send_and_return else 1.0
        return (
            self.moe_layers
            * self.experts_per_token
            * self.hidden_bytes(activation_bits)
            * multiplier
            * remote_expert_fraction
        )


def _validate_bits(bits: float) -> None:
    if bits <= 0:
        raise ValueError("bit width must be positive")


def _validate_overhead(overhead: float) -> None:
    if overhead < 0:
        raise ValueError("overhead_fraction cannot be negative")


MODEL_SPECS: dict[str, ModelSpec] = {
    "qwen3.8-27b": ModelSpec(
        key="qwen3.8-27b",
        name="Qwen3.8-27B",
        total_parameters=27e9,
        active_parameters=27e9,
        num_layers=64,
        dense_layers=64,
        hidden_size=5120,
        context_length=262_144,
        architecture="Dense hybrid: 48 Gated DeltaNet + 16 gated full-attention layers",
        source="https://huggingface.co/Qwen/Qwen3.8-27B",
        notes=(
            "Official model card reports 27B parameters, hidden size 5120 and 64 layers with a "
            "16 x [3 Gated DeltaNet + 1 gated full-attention] layout. At generic Q4 plus 5% "
            "metadata overhead this simulator estimates 14.175 GB of weight storage."
        ),
    ),
    "kimi-k3": ModelSpec(
        key="kimi-k3",
        name="Kimi K3",
        total_parameters=2.8e12,
        active_parameters=104e9,
        num_layers=93,
        dense_layers=1,
        hidden_size=7168,
        num_experts=896,
        experts_per_token=16,
        shared_experts=2,
        moe_intermediate_size=3072,
        context_length=1_048_576,
        architecture="MoE: 69 KDA + 24 gated MLA attention layers, Latent MoE",
        source="https://huggingface.co/moonshotai/Kimi-K3",
        notes=(
            "Vendor reports 2.8T total / 104B active parameters and 2 shared experts per MoE layer. "
            "The released MXFP4 config explicitly excludes shared_experts (and several other modules) "
            "from 4-bit quantization, so uniform-bit sizing is an optimistic research abstraction."
        ),
    ),
    "glm-5.2": ModelSpec(
        key="glm-5.2",
        name="GLM-5.2",
        total_parameters=744e9,
        active_parameters=40e9,
        num_layers=78,
        dense_layers=3,
        hidden_size=6144,
        num_experts=256,
        experts_per_token=8,
        shared_experts=1,
        moe_intermediate_size=2048,
        context_length=1_000_000,
        architecture="MoE + DSA/IndexShare",
        source="https://huggingface.co/zai-org/GLM-5.2",
        notes="744B-A40B configuration; 3 dense + 75 MoE layers; 1 always-active shared expert per MoE layer.",
    ),
    "glm-5.3": ModelSpec(
        key="glm-5.3",
        name="GLM-5.3",
        total_parameters=744e9,
        active_parameters=40e9,
        num_layers=78,
        dense_layers=3,
        hidden_size=6144,
        num_experts=256,
        experts_per_token=8,
        shared_experts=1,
        moe_intermediate_size=2048,
        context_length=1_000_000,
        architecture="MoE + DSA/IndexShare",
        source="https://z.ai/blog/glm-5.3",
        notes=(
            "Z.ai states GLM-5.3 uses the same base model as GLM-5.2 and changes post-training only. "
            "Until the GLM-5.3 weights/config are published, this preset intentionally aliases the "
            "GLM-5.2 base architecture, including 1 shared expert per MoE layer."
        ),
    ),
}

ALIASES = {
    "qwen": "qwen3.8-27b",
    "qwen27": "qwen3.8-27b",
    "qwen3.8": "qwen3.8-27b",
    "qwen3.8-27b": "qwen3.8-27b",
    "k3": "kimi-k3",
    "kimi": "kimi-k3",
    "glm52": "glm-5.2",
    "glm5.2": "glm-5.2",
    "glm53": "glm-5.3",
    "glm5.3": "glm-5.3",
}


def get_model(key: str) -> ModelSpec:
    normalized = key.strip().lower()
    normalized = ALIASES.get(normalized, normalized)
    try:
        return MODEL_SPECS[normalized]
    except KeyError as exc:
        available = ", ".join(sorted(MODEL_SPECS))
        raise KeyError(f"unknown model {key!r}; available: {available}") from exc
